kaikas:
  authKey:
    KASKWIM459K2J82E1N7JY2HZ:cBr-HHL0S5AenhZqeendbpw4vbr3oEW2bBxMIJEr

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@cluster0.yogevbk.mongodb.net/?retryWrites=true&w=majority